- hosts: all
  become: true
  gather_facts: true
  pre_tasks:
  - name: Install python2 for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-setuptools)
    register: output
    changed_when: output.stdout != ""
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
- hosts: database
  become: true
  roles:
    - postgres
- hosts: metabase
  become: true
  roles:
    - java
    - mb_install
    - nginx
